# Generated by Django 5.1.3 on 2024-11-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_created_date_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
