# Generated by Django 5.1.3 on 2024-11-22 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_sub_content_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='description',
            new_name='author',
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(upload_to='contents/%Y/%m'),
        ),
    ]
