# Generated by Django 5.1.3 on 2024-11-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_description_content_author_content_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
