# Generated by Django 5.1.3 on 2024-11-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_image_content_image_url_content_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image_url',
        ),
    ]
