# Generated by Django 5.1.3 on 2024-11-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_content_image_file_remove_content_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
